"""replace forigen key

Revision ID: 2a8fb081756e
Revises: aecd769a8d64
Create Date: 2025-01-10 03:10:56.302103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a8fb081756e'
down_revision: Union[str, None] = 'aecd769a8d64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('history_game_heroes_history_game_id_fkey', 'history_game_heroes', type_='foreignkey')
    op.create_foreign_key(None, 'history_game_heroes', 'history_games', ['history_game_id'], ['id'])
    op.drop_constraint('history_game_operations_history_game_id_fkey', 'history_game_operations', type_='foreignkey')
    op.create_foreign_key(None, 'history_game_operations', 'history_games', ['history_game_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'history_game_operations', type_='foreignkey')
    op.create_foreign_key('history_game_operations_history_game_id_fkey', 'history_game_operations', 'games', ['history_game_id'], ['id'])
    op.drop_constraint(None, 'history_game_heroes', type_='foreignkey')
    op.create_foreign_key('history_game_heroes_history_game_id_fkey', 'history_game_heroes', 'games', ['history_game_id'], ['id'])
    # ### end Alembic commands ###
