"""forigen keys

Revision ID: 2b31c6aafc49
Revises: ec66a4b44ac0
Create Date: 2025-01-09 03:40:58.327579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b31c6aafc49'
down_revision: Union[str, None] = 'ec66a4b44ac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'game_heroes', 'games', ['game_id'], ['id'])
    op.create_foreign_key(None, 'game_heroes', 'heroes', ['hero_id'], ['id'])
    op.create_foreign_key(None, 'game_operations', 'games', ['game_id'], ['id'])
    op.create_foreign_key(None, 'games', 'tournaments', ['tournament_id'], ['id'])
    op.create_foreign_key(None, 'history_game_heroes', 'heroes', ['hero_id'], ['id'])
    op.create_foreign_key(None, 'history_game_heroes', 'games', ['history_game_id'], ['id'])
    op.create_foreign_key(None, 'history_game_operations', 'games', ['history_game_id'], ['id'])
    op.create_foreign_key(None, 'history_games', 'heroes', ['win_hero_id'], ['id'])
    op.create_foreign_key(None, 'history_games', 'tournaments', ['tournament_id'], ['id'])
    op.create_foreign_key(None, 'tournament_blinds', 'tournaments', ['tournament_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournament_blinds', type_='foreignkey')
    op.drop_constraint(None, 'history_games', type_='foreignkey')
    op.drop_constraint(None, 'history_games', type_='foreignkey')
    op.drop_constraint(None, 'history_game_operations', type_='foreignkey')
    op.drop_constraint(None, 'history_game_heroes', type_='foreignkey')
    op.drop_constraint(None, 'history_game_heroes', type_='foreignkey')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_constraint(None, 'game_operations', type_='foreignkey')
    op.drop_constraint(None, 'game_heroes', type_='foreignkey')
    op.drop_constraint(None, 'game_heroes', type_='foreignkey')
    # ### end Alembic commands ###
