"""guaranteed_amount

Revision ID: 628dc81308b9
Revises: 0cd107439199
Create Date: 2025-01-22 02:31:47.198180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '628dc81308b9'
down_revision: Union[str, None] = '0cd107439199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('guaranteed_amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'guaranteed_amount')
    # ### end Alembic commands ###
