"""Enum Fix

Revision ID: a89a4427ed56
Revises: 2b31c6aafc49
Create Date: 2025-01-09 21:12:47.958370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a89a4427ed56'
down_revision: Union[str, None] = '2b31c6aafc49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_operations', 'operation',
               existing_type=postgresql.ENUM('start', 'end', 'pause', 'next_level', 'time_break', name='gameoperations'),
               type_=sa.Enum('start', 'end', 'pause', 'next_level', 'time_break', name='gameoperationsenum'),
               existing_nullable=False)
    op.alter_column('history_game_operations', 'operation',
               existing_type=postgresql.ENUM('start', 'end', 'pause', 'next_level', 'time_break', name='gameoperations'),
               type_=sa.Enum('start', 'end', 'pause', 'next_level', 'time_break', name='gameoperationsenum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('history_game_operations', 'operation',
               existing_type=sa.Enum('start', 'end', 'pause', 'next_level', 'time_break', name='gameoperationsenum'),
               type_=postgresql.ENUM('start', 'end', 'pause', 'next_level', 'time_break', name='gameoperations'),
               existing_nullable=False)
    op.alter_column('game_operations', 'operation',
               existing_type=sa.Enum('start', 'end', 'pause', 'next_level', 'time_break', name='gameoperationsenum'),
               type_=postgresql.ENUM('start', 'end', 'pause', 'next_level', 'time_break', name='gameoperations'),
               existing_nullable=False)
    # ### end Alembic commands ###
