"""add ended_at in game

Revision ID: aecd769a8d64
Revises: a89a4427ed56
Create Date: 2025-01-10 03:05:12.202931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aecd769a8d64'
down_revision: Union[str, None] = 'a89a4427ed56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('ended_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'ended_at')
    # ### end Alembic commands ###
