"""not null

Revision ID: ec66a4b44ac0
Revises: ab0372a7f0b7
Create Date: 2025-01-08 00:39:36.046406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec66a4b44ac0'
down_revision: Union[str, None] = 'ab0372a7f0b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blinds', 'small_blind',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('blinds', 'big_blind',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('blinds', 'ante',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('blinds', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('blinds', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('game_heroes', 'game_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('game_heroes', 'hero_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('game_heroes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('game_heroes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('game_operations', 'game_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('game_operations', 'operation',
               existing_type=postgresql.ENUM('start', 'end', 'pause', 'next_level', 'time_break', name='gameoperations'),
               nullable=False)
    op.alter_column('game_operations', 'success_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('game_operations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('game_operations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('games', 'tournament_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('games', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('games', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('heroes', 'fullname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('heroes', 'total_win',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('heroes', 'total_lose',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('heroes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('heroes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('history_game_heroes', 'history_game_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('history_game_heroes', 'hero_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('history_game_heroes', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('history_game_heroes', 'ended_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('history_game_heroes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('history_game_heroes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('history_game_operations', 'history_game_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('history_game_operations', 'operation',
               existing_type=postgresql.ENUM('start', 'end', 'pause', 'next_level', 'time_break', name='gameoperations'),
               nullable=False)
    op.alter_column('history_game_operations', 'success_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('history_game_operations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('history_game_operations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('history_games', 'tournament_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('history_games', 'win_hero_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('history_games', 'win_total',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('history_games', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('history_games', 'ended_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('history_games', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('history_games', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tournament_blinds', 'tournament_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tournament_blinds', 'blind_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tournament_blinds', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tournament_blinds', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tournaments', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tournaments', 'price_rebuy',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tournaments', 'chip_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tournaments', 'level_minutes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tournaments', 'break_minutes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tournaments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tournaments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tournaments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tournaments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tournaments', 'break_minutes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tournaments', 'level_minutes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tournaments', 'chip_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tournaments', 'price_rebuy',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tournaments', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tournament_blinds', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tournament_blinds', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tournament_blinds', 'blind_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tournament_blinds', 'tournament_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('history_games', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('history_games', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('history_games', 'ended_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('history_games', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('history_games', 'win_total',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('history_games', 'win_hero_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('history_games', 'tournament_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('history_game_operations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('history_game_operations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('history_game_operations', 'success_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('history_game_operations', 'operation',
               existing_type=postgresql.ENUM('start', 'end', 'pause', 'next_level', 'time_break', name='gameoperations'),
               nullable=True)
    op.alter_column('history_game_operations', 'history_game_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('history_game_heroes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('history_game_heroes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('history_game_heroes', 'ended_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('history_game_heroes', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('history_game_heroes', 'hero_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('history_game_heroes', 'history_game_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('heroes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('heroes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('heroes', 'total_lose',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('heroes', 'total_win',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('heroes', 'fullname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('games', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('games', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('games', 'tournament_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('game_operations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('game_operations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('game_operations', 'success_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('game_operations', 'operation',
               existing_type=postgresql.ENUM('start', 'end', 'pause', 'next_level', 'time_break', name='gameoperations'),
               nullable=True)
    op.alter_column('game_operations', 'game_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('game_heroes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('game_heroes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('game_heroes', 'hero_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('game_heroes', 'game_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('blinds', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('blinds', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('blinds', 'ante',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('blinds', 'big_blind',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('blinds', 'small_blind',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
