"""init

Revision ID: f7d3a724e55a
Revises: 
Create Date: 2025-01-10 13:44:43.471749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7d3a724e55a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blinds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('small_blind', sa.Integer(), nullable=False),
    sa.Column('big_blind', sa.Integer(), nullable=False),
    sa.Column('ante', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blinds_id'), 'blinds', ['id'], unique=False)
    op.create_table('heroes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fullname', sa.String(), nullable=False),
    sa.Column('total_win', sa.Integer(), nullable=False),
    sa.Column('total_lose', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heroes_id'), 'heroes', ['id'], unique=False)
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price_rebuy', sa.Integer(), nullable=False),
    sa.Column('chip_count', sa.Integer(), nullable=False),
    sa.Column('level_minutes', sa.Integer(), nullable=False),
    sa.Column('break_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournaments_id'), 'tournaments', ['id'], unique=False)
    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_index(op.f('ix_games_tournament_id'), 'games', ['tournament_id'], unique=False)
    op.create_table('history_games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('win_hero_id', sa.Integer(), nullable=False),
    sa.Column('win_total', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['win_hero_id'], ['heroes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_games_id'), 'history_games', ['id'], unique=False)
    op.create_index(op.f('ix_history_games_tournament_id'), 'history_games', ['tournament_id'], unique=False)
    op.create_index(op.f('ix_history_games_win_hero_id'), 'history_games', ['win_hero_id'], unique=False)
    op.create_table('tournament_blinds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('blind_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournament_blinds_blind_id'), 'tournament_blinds', ['blind_id'], unique=False)
    op.create_index(op.f('ix_tournament_blinds_id'), 'tournament_blinds', ['id'], unique=False)
    op.create_index(op.f('ix_tournament_blinds_tournament_id'), 'tournament_blinds', ['tournament_id'], unique=False)
    op.create_table('game_heroes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('hero_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['hero_id'], ['heroes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_heroes_game_id'), 'game_heroes', ['game_id'], unique=False)
    op.create_index(op.f('ix_game_heroes_hero_id'), 'game_heroes', ['hero_id'], unique=False)
    op.create_index(op.f('ix_game_heroes_id'), 'game_heroes', ['id'], unique=False)
    op.create_table('game_operations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.Enum('start', 'end', 'pause', 'unpause', 'next_level', 'time_break', name='gameoperationsenum'), nullable=False),
    sa.Column('success_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_operations_game_id'), 'game_operations', ['game_id'], unique=False)
    op.create_index(op.f('ix_game_operations_id'), 'game_operations', ['id'], unique=False)
    op.create_table('history_game_heroes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('history_game_id', sa.Integer(), nullable=False),
    sa.Column('hero_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hero_id'], ['heroes.id'], ),
    sa.ForeignKeyConstraint(['history_game_id'], ['history_games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_game_heroes_hero_id'), 'history_game_heroes', ['hero_id'], unique=False)
    op.create_index(op.f('ix_history_game_heroes_history_game_id'), 'history_game_heroes', ['history_game_id'], unique=False)
    op.create_index(op.f('ix_history_game_heroes_id'), 'history_game_heroes', ['id'], unique=False)
    op.create_table('history_game_operations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('history_game_id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.Enum('start', 'end', 'pause', 'unpause', 'next_level', 'time_break', name='gameoperationsenum'), nullable=False),
    sa.Column('success_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['history_game_id'], ['history_games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_game_operations_history_game_id'), 'history_game_operations', ['history_game_id'], unique=False)
    op.create_index(op.f('ix_history_game_operations_id'), 'history_game_operations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_history_game_operations_id'), table_name='history_game_operations')
    op.drop_index(op.f('ix_history_game_operations_history_game_id'), table_name='history_game_operations')
    op.drop_table('history_game_operations')
    op.drop_index(op.f('ix_history_game_heroes_id'), table_name='history_game_heroes')
    op.drop_index(op.f('ix_history_game_heroes_history_game_id'), table_name='history_game_heroes')
    op.drop_index(op.f('ix_history_game_heroes_hero_id'), table_name='history_game_heroes')
    op.drop_table('history_game_heroes')
    op.drop_index(op.f('ix_game_operations_id'), table_name='game_operations')
    op.drop_index(op.f('ix_game_operations_game_id'), table_name='game_operations')
    op.drop_table('game_operations')
    op.drop_index(op.f('ix_game_heroes_id'), table_name='game_heroes')
    op.drop_index(op.f('ix_game_heroes_hero_id'), table_name='game_heroes')
    op.drop_index(op.f('ix_game_heroes_game_id'), table_name='game_heroes')
    op.drop_table('game_heroes')
    op.drop_index(op.f('ix_tournament_blinds_tournament_id'), table_name='tournament_blinds')
    op.drop_index(op.f('ix_tournament_blinds_id'), table_name='tournament_blinds')
    op.drop_index(op.f('ix_tournament_blinds_blind_id'), table_name='tournament_blinds')
    op.drop_table('tournament_blinds')
    op.drop_index(op.f('ix_history_games_win_hero_id'), table_name='history_games')
    op.drop_index(op.f('ix_history_games_tournament_id'), table_name='history_games')
    op.drop_index(op.f('ix_history_games_id'), table_name='history_games')
    op.drop_table('history_games')
    op.drop_index(op.f('ix_games_tournament_id'), table_name='games')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_tournaments_id'), table_name='tournaments')
    op.drop_table('tournaments')
    op.drop_index(op.f('ix_heroes_id'), table_name='heroes')
    op.drop_table('heroes')
    op.drop_index(op.f('ix_blinds_id'), table_name='blinds')
    op.drop_table('blinds')
    # ### end Alembic commands ###
